export interface LabContract {
  title: string;
  competency: string;
  domain: string;
  mission: string;
  outcome: string;
  entities: string[];
  seededDefects: string[];
  verificationGates: string[];
  agentWorkflow: string[];
  workingDeliverables: string[];
  masterySignals: string[];
}

export const labContract: LabContract = {
  "title": "Review Checklist Skill Pack",
  "competency": "05. Skill Packaging - Workflow packaging into reusable skills",
  "domain": "Reusable experienced code-review skill with trigger evals",
  "mission": "Package a repeated code review checklist into a focused skill and use it against the provided React change.",
  "outcome": "A repeated experienced review workflow becomes a runnable team skill with an eval harness.",
  "entities": [
    "SKILL.md",
    "review checklist",
    "trigger eval",
    "finding schema"
  ],
  "seededDefects": [
    "skill triggers on generic cleanup requests",
    "security checklist omits unsafe HTML rendering",
    "finding output has no severity contract"
  ],
  "verificationGates": [
    "skill trigger eval",
    "sample diff review",
    "schema validation",
    "human triage review"
  ],
  "agentWorkflow": [
    "Ask the coding agent to inspect this lab contract, starter code, docs, and tests before proposing a plan.",
    "Revise the agent plan so it exercises the competency practice and avoids the common mistake.",
    "Implement the smallest working change that addresses the seeded defects.",
    "Run the verification gates and capture command evidence before writing the final review note."
  ],
  "workingDeliverables": [
    "In-repo skill folder.",
    "Eval or smoke harness for trigger quality and output shape.",
    "Review findings generated by the skill and then human-triaged.",
    "A refined skill version based on the eval result."
  ],
  "masterySignals": [
    "Create a focused `SKILL.md` with precise trigger description, when-not-to-use guidance, and a concrete example.",
    "Package reference checklists separately so the skill body stays lean.",
    "Run the skill against the provided diff and capture findings.",
    "Add eval cases that prove the skill triggers correctly and avoids noisy use."
  ]
};
