export interface LabContract {
  title: string;
  competency: string;
  domain: string;
  mission: string;
  outcome: string;
  entities: string[];
  seededDefects: string[];
  verificationGates: string[];
  agentWorkflow: string[];
  workingDeliverables: string[];
  masterySignals: string[];
}

export const labContract: LabContract = {
  "title": "Flaky Checkout E2E Rescue",
  "competency": "04. Test Automation - Reliable E2E test generation",
  "domain": "Checkout E2E suite for tax and payment boundaries",
  "mission": "Replace brittle checkout tests with a reliable Playwright suite that uses user-facing locators and web-first assertions.",
  "outcome": "The checkout suite becomes trustworthy enough to protect a refactor.",
  "entities": [
    "cart",
    "payment authorization",
    "tax quote",
    "Playwright trace"
  ],
  "seededDefects": [
    "test uses fixed sleep after payment authorization",
    "selector depends on CSS class generated by the design system",
    "payment mock leaks state between tests"
  ],
  "verificationGates": [
    "role locator audit",
    "parallel repeat run",
    "trace capture",
    "payment boundary fixture"
  ],
  "agentWorkflow": [
    "Ask the coding agent to inspect this lab contract, starter code, docs, and tests before proposing a plan.",
    "Revise the agent plan so it exercises the competency practice and avoids the common mistake.",
    "Implement the smallest working change that addresses the seeded defects.",
    "Run the verification gates and capture command evidence before writing the final review note."
  ],
  "workingDeliverables": [
    "Playwright tests for the main checkout flows.",
    "Deterministic mocks and fixtures.",
    "Any app accessibility/testability fixes required for role locators.",
    "Repeated-run evidence and trace/report configuration."
  ],
  "masterySignals": [
    "Replace brittle selectors and fixed waits with role locators and web-first assertions.",
    "Mock payment, tax, clock, or third-party boundaries without mocking away checkout behavior.",
    "Make every test independent and parallel-safe.",
    "Run repeated local passes and preserve traces or reports for failures."
  ]
};
