import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execFileSync, spawnSync } from "node:child_process";

const argument = name => process.argv[process.argv.indexOf(name) + 1];
const app = process.cwd(), exercise = path.resolve(app, "..");
const contract = JSON.parse(fs.readFileSync(path.join(app, "evidence-contract.json")));
const script = argument("--command"), out = argument("--out");
assert.ok(contract.captureCommands.includes(script), "Choose a focused command from this exercise's setup");
assert.match(script, /^[a-z0-9:-]+$/);
assert.ok(process.argv.includes("--out") && out, "Supply --out <capture-path>");
const output = path.resolve(app, out), relative = path.relative(path.join(exercise, "evidence/commands"), output);
assert.ok(relative && !relative.startsWith("..") && !path.isAbsolute(relative) && relative !== "verify.txt", "Write focused output inside evidence/commands; verify.txt uses evidence:capture");
assert.ok(!fs.existsSync(output), "Preserve the previous capture before writing a new attempt");
let parent = path.dirname(output);
while (!fs.existsSync(parent)) parent = path.dirname(parent);
const realParent = path.relative(fs.realpathSync(exercise), fs.realpathSync(parent));
assert.ok(!realParent.startsWith("..") && !path.isAbsolute(realParent), "Capture directory escapes the exercise through a link");
const cwd = process.argv.includes("--cwd") ? path.resolve(app, argument("--cwd")) : app;
const git = (root, args) => execFileSync("git", args, { cwd: root, stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" }).trim();
const common = root => fs.realpathSync(path.resolve(root, git(root, ["rev-parse", "--git-common-dir"])));
assert.equal(common(cwd), common(app), "Use this repository's linked worktree");
assert.equal(git(cwd, ["rev-parse", "--show-prefix"]), git(app, ["rev-parse", "--show-prefix"]), "Capture from the matching app path in its worktree");
assert.equal(git(cwd, ["diff", "HEAD", "--", "."]), "", "Commit application changes before capturing");
assert.equal(git(cwd, ["ls-files", "--others", "--exclude-standard", "--", "."]), "", "Commit new application files before capturing");
const sha = git(cwd, ["rev-parse", "HEAD"]), started = new Date().toISOString();
const command = process.platform === "win32" ? (process.env.ComSpec ?? "cmd.exe") : "npm";
const args = process.platform === "win32" ? ["/d", "/s", "/c", "npm run " + script] : ["run", script];
const result = spawnSync(command, args, { cwd, encoding: "utf8", maxBuffer: 32 * 1024 * 1024, env: process.env });
const finished = new Date().toISOString();
assert.ok(!result.error && Number.isInteger(result.status), "Focused command could not complete: " + result.error?.message);
assert.equal(git(cwd, ["rev-parse", "HEAD"]), sha, "Command changed its source commit");
assert.equal(git(cwd, ["diff", "HEAD", "--", "."]), "", "Command changed application source");
assert.equal(git(cwd, ["ls-files", "--others", "--exclude-standard", "--", "."]), "", "Command created application files");
fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, "Command: npm run " + script + "\nReviewed SHA: " + sha + "\nStarted at: " + started + "\nFinished at: " + finished + "\n\n" + (result.stdout ?? "") + (result.stderr ?? "") + "\nexit code: " + result.status + "\n");
console.log("Captured npm run " + script + " at " + sha + " (exit " + result.status + ") to " + output);
process.exitCode = result.status;
